### ISSUE TITLE
UI breaks on TypeError: Object of type 'bytes' is not JSON serializable

### ISSUE THREAD

**Issue by JohnLZeller** [puckel/docker-airflow#116]
I am running off of `latest`, which at this time is `1.8.2`.

I setup a simple Hello World with my own DAG, installed using a simple `docker-compose.yml`.

```
# docker-compose.yml
version: '2'
services:
  airflow:
    image: puckel/docker-airflow
    volumes:
      - ./dags/:/usr/local/airflow/dags/
      - ./plugins/:/usr/local/airflow/plugins/
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    environment:
      LOAD_EX: n
```

My `requirements.txt` is really small too.

```
# requirements.txt
beautifulsoup4==4.6.0
bs4==0.0.1
```

The issue comes when I am attempting to look at my DAG.
Attempting to visit: `http://localhost:8080/admin/airflow/tree?dag_id=mydag` produces the following traceback. And this happens for any link relating to the dag, except for `trigger` it seems.

```

                          ____/ (  (    )   )  \___
                         /( (  (  )   _    ))  )   )\
                       ((     (   )(    )  )   (   )  )
                     ((/  ( _(   )   (   _) ) (  () )  )
                    ( (  ( (_)   ((    (   )  .((_ ) .  )_
                   ( (  )    (      (  )    )   ) . ) (   )
                  (  (   (  (   ) (  _  ( _) ).  ) . ) ) ( )
                  ( (  (   ) (  )   (  ))     ) _)(   )  )  )
                 ( (  ( \ ) (    (_  ( ) ( )  )   ) )  )) ( )
                  (  (   (  (   (_ ( ) ( _    )  ) (  )  )   )
                 ( (  ( (  (  )     (_  )  ) )  _)   ) _( ( )
                  ((  (   )(    (     _    )   _) _(_ (  (_ )
                   (_((__(_(__(( ( ( |  ) ) ) )_))__))_)___)
                   ((__)        \\||lll|l||///          \_))
                            (   /(/ (  )  ) )\   )
                          (    ( ( ( | | ) ) )\   )
                           (   /(| / ( )) ) ) )) )
                         (     ( ((((_(|)_)))))     )
                          (      ||\(|(|)|/||     )
                        (        |(||(||)||||        )
                          (     //|/l|||)|\\ \     )
                        (/ / //  /|//||||\\  \ \  \ _)
-------------------------------------------------------------------------------
Node: 303f7161391a
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login.py", line 755, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airflow/www/utils.py", line 219, in view_func
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airflow/www/utils.py", line 125, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airflow/www/views.py", line 1252, in tree
    'num_runs': num_runs})
  File "/usr/local/lib/python3.6/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_wtf/form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wtforms/form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wtforms/form.py", line 132, in process
    field.process(formdata)
  File "/usr/local/lib/python3.6/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/usr/local/lib/python3.6/site-packages/flask_wtf/csrf.py", line 134, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/usr/local/lib/python3.6/site-packages/flask_wtf/csrf.py", line 47, in generate_csrf
    setattr(g, field_name, s.dumps(session[field_name]))
  File "/usr/local/lib/python3.6/site-packages/itsdangerous.py", line 565, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "/usr/local/lib/python3.6/site-packages/itsdangerous.py", line 847, in dump_payload
    json = super(URLSafeSerializerMixin, self).dump_payload(obj)
  File "/usr/local/lib/python3.6/site-packages/itsdangerous.py", line 550, in dump_payload
    return want_bytes(self.serializer.dumps(obj))
  File "/usr/local/lib/python3.6/site-packages/itsdangerous.py", line 51, in dumps
    return json.dumps(obj, separators=(',', ':'))
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
```

**Comment by JohnLZeller** [comment]
Looks like this happens without a custom setup too. Just by pulling tip and running `docker-compose -f docker-compose-LocalExecutor.yml up -d`

**Comment by bernardocaldas** [comment]
Hi John, have you managed to correct this issue? I've run into it as well...

**Comment by bernardocaldas** [comment]
Got it. You've got to clear your cookies. Most likely you were running python2 and now running python3, but the cookies are still set to python2.

**Comment by JohnLZeller** [comment]
This was indeed it, thanks @bernardocaldas!

**Comment by FlorianDietz** [comment]
_How_ do I clear the cookies?

**Comment by scordata** [comment]
+1
I just ran into this as well - What's the method for clearing the cookies here?

**Comment by fclesio** [comment]
@FlorianDietz @scordata 

**In Chrome**

1. On your computer, open Chrome.
2. At the top right, click More .
3. Click More tools Clear browsing data.
4. At the top, choose a time range. To delete everything, select All time.
5. Next to "Cookies and other site data" and "Cached images and files," check the boxes.
6. Click Clear data.

**Comment by nkpydev** [comment]
Thanks! I ran into same problem with change of Python 2.7 to Python 3.7 to use F-Strings and the Flask web application started giving this error!
Just simple cookie clear on the Chrome was easier than thought, but my mind didn't venture there, Thanks again for guiding in the right direction.

**Comment by davidasync** [comment]
> Got it. You've got to clear your cookies. Most likely you were running python2 and now running python3, but the cookies are still set to python2.

Works for me
