### ISSUE TITLE
Numpy is looking for a dynamic library (libblas.so.3) and doesn't find it.

### ISSUE THREAD

**Issue by emirot** [puckel/docker-airflow#119]
Looks like [numpy](https://github.com/numpy/numpy) has been updated latetly to 1.13.2  

Doing:  `docker run puckel/docker-airflow`

I get : 
```
 docker run puckel/docker-airflow
Unable to find image 'puckel/docker-airflow:latest' locally
latest: Pulling from puckel/docker-airflow
aa18ad1a0d33: Already exists 
1b1ad4542c99: Already exists 
f55f6bdb976a: Already exists 
c91d00a04662: Already exists 
37de53ca9f34: Already exists 
a7c212f785d0: Pull complete 
4d86a82f9b86: Pull complete 
9122063cd6d3: Pull complete 
b4c9ded248c3: Pull complete 
Digest: sha256:2e0b8bfd4775e4a9f27cf25214bc2adbe7c95046074654e3cef2f6ca5db90aff
Status: Downloaded newer image for puckel/docker-airflow:latest
Initialize database...
[2017-09-28 22:39:30,395] {__init__.py:57} INFO - Using executor SequentialExecutor
DB: sqlite:////usr/local/airflow/airflow.db
[2017-09-28 22:39:30,788] {db.py:287} INFO - Creating tables
/usr/local/lib/python3.6/site-packages/airflow/www/app.py:23: FlaskWTFDeprecationWarning: "flask_wtf.CsrfProtect" has been renamed to "CSRFProtect" and will be removed in 1.0.
  csrf = CsrfProtect()
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> e3a246e0dc1, current schema
INFO  [alembic.runtime.migration] Running upgrade e3a246e0dc1 -> 1507a7289a2f, create is_encrypted
/usr/local/lib/python3.6/site-packages/alembic/util/messaging.py:69: UserWarning: Skipping unsupported ALTER for creation of implicit constraint
  warnings.warn(msg)
INFO  [alembic.runtime.migration] Running upgrade 1507a7289a2f -> 13eb55f81627, maintain history for compatibility with earlier migrations
INFO  [alembic.runtime.migration] Running upgrade 13eb55f81627 -> 338e90f54d61, More logging into task_isntance
INFO  [alembic.runtime.migration] Running upgrade 338e90f54d61 -> 52d714495f0, job_id indices
INFO  [alembic.runtime.migration] Running upgrade 52d714495f0 -> 502898887f84, Adding extra to Log
INFO  [alembic.runtime.migration] Running upgrade 502898887f84 -> 1b38cef5b76e, add dagrun
INFO  [alembic.runtime.migration] Running upgrade 1b38cef5b76e -> 2e541a1dcfed, task_duration
INFO  [alembic.runtime.migration] Running upgrade 2e541a1dcfed -> 40e67319e3a9, dagrun_config
INFO  [alembic.runtime.migration] Running upgrade 40e67319e3a9 -> 561833c1c74b, add password column to user
INFO  [alembic.runtime.migration] Running upgrade 561833c1c74b -> 4446e08588, dagrun start end
INFO  [alembic.runtime.migration] Running upgrade 4446e08588 -> bbc73705a13e, Add notification_sent column to sla_miss
INFO  [alembic.runtime.migration] Running upgrade bbc73705a13e -> bba5a7cfc896, Add a column to track the encryption state of the 'Extra' field in connection
INFO  [alembic.runtime.migration] Running upgrade bba5a7cfc896 -> 1968acfc09e3, add is_encrypted column to variable table
INFO  [alembic.runtime.migration] Running upgrade 1968acfc09e3 -> 2e82aab8ef20, rename user table
INFO  [alembic.runtime.migration] Running upgrade 2e82aab8ef20 -> 211e584da130, add TI state index
INFO  [alembic.runtime.migration] Running upgrade 211e584da130 -> 64de9cddf6c9, add task fails journal table
INFO  [alembic.runtime.migration] Running upgrade 64de9cddf6c9 -> f2ca10b85618, add dag_stats table
INFO  [alembic.runtime.migration] Running upgrade f2ca10b85618 -> 4addfa1236f1, Add fractional seconds to mysql tables
INFO  [alembic.runtime.migration] Running upgrade 4addfa1236f1 -> 8504051e801b, xcom dag task indices
INFO  [alembic.runtime.migration] Running upgrade 8504051e801b -> 5e7d17757c7a, add pid field to TaskInstance
INFO  [alembic.runtime.migration] Running upgrade 5e7d17757c7a -> 127d2bf2dfa7, Add dag_id/state index on dag_run table
Done.
[2017-09-28 22:39:35,726] {__init__.py:57} INFO - Using executor SequentialExecutor
/usr/local/lib/python3.6/site-packages/airflow/www/app.py:23: FlaskWTFDeprecationWarning: "flask_wtf.CsrfProtect" has been renamed to "CSRFProtect" and will be removed in 1.0.
  csrf = CsrfProtect()
/usr/local/lib/python3.6/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.
  .format(x=modname), ExtDeprecationWarning
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: libblas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 28, in <module>
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/airflow/bin/cli.py", line 734, in webserver
    app = cached_app(conf)
  File "/usr/local/lib/python3.6/site-packages/airflow/www/app.py", line 161, in cached_app
    app = create_app(config)
  File "/usr/local/lib/python3.6/site-packages/airflow/www/app.py", line 60, in create_app
    from airflow.www import views
  File "/usr/local/lib/python3.6/site-packages/airflow/www/views.py", line 68, in <module>
    from airflow.utils.json import json_ser
  File "/usr/local/lib/python3.6/site-packages/airflow/utils/json.py", line 22, in <module>
    import numpy as np
  File "/usr/local/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python3.6/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: libblas.so.3: cannot open shared object file: No such file or directory
``` 

Logging into the container I have numpy 1.13.2 which is the latest version. If I build the image I have version 1.13.1 and I don't understand why, I've used --no-cache.

**Comment by shoumitragametime** [comment]
Just ran into this error myself.

**Comment by mhousley** [comment]
You can get a working image of release 1.8.2 by pulling with a specific older image by digest. sha256:b507fc7480448357cc91f86d51c76e6a71c86c93a1573dd13734392040209e50 works. For instance, you can run
`docker run -d -p 8080:8080 puckel/docker-airflow@sha256:b507fc7480448357cc91f86d51c76e6a71c86c93a1573dd13734392040209e50`
or paste the digest into one of the compose files.

**Comment by mhousley** [comment]
It looks like the current build is no longer broken.

**Comment by emirot** [comment]
@mhousley  you're right, I'm closing the issue.
