### ISSUE TITLE
Scheduler not picking up + croniter.py error

### ISSUE THREAD

**Issue by bgamign** [puckel/docker-airflow#131]
Hi. I am having some issue with Airflow scheduler. It does not pick up a schedule for certain DAGs where the schedule is not "None" and it generates some error logs related to croniter.py 
Does anyone have a similar issue with this?
I am using:
apache-airflow (1.8.2)
celery (3.1.17)
redis (2.10.6)

Here is the log:
[2017-11-20 19:12:02,738] {jobs.py:1443} INFO - Heartbeating the executor
Process DagFileProcessor390037-Process:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
 self.run()
File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
  self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.6/site-packages/airflow/jobs.py", line 347, in helper
  pickle_dags)
 File "/usr/local/lib/python3.6/site-packages/airflow/utils/db.py", line 53, in wrapper
 result = func(*args, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/airflow/jobs.py", line 1584, in process_file
  self._process_dags(dagbag, dags, ti_keys_to_schedule)
File "/usr/local/lib/python3.6/site-packages/airflow/jobs.py", line 1173, in _process_dags
dag_run = self.create_dag_run(dag)
 File "/usr/local/lib/python3.6/site-packages/airflow/utils/db.py", line 53, in wrapper
result = func(*args, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/airflow/jobs.py", line 793, in create_dag_run
next_run_date = dag.normalize_schedule(min(task_start_dates))
File "/usr/local/lib/python3.6/site-packages/airflow/models.py", line 2838, in normalize_schedule
following = self.following_schedule(dttm)
File "/usr/local/lib/python3.6/site-packages/airflow/models.py", line 2823, in following_schedule
return cron.get_next(datetime)
File "/usr/local/lib/python3.6/site-packages/croniter/croniter.py", line 100, in get_next
return self._get_next(ret_type or self._ret_type, is_prev=False)
File "/usr/local/lib/python3.6/site-packages/croniter/croniter.py", line 190, in _get_next
nth_weekday_of_month, is_prev)
File "/usr/local/lib/python3.6/site-packages/croniter/croniter.py", line 231, in _calc
dst = now = self._timestamp_to_datetime(now + sign * offset)
TypeError: must be str, not int
10.0.241.247 - - [20/Nov/2017:19:12:03 +0000] "GET /admin/ HTTP/1.1" 200 103434 "-" "ELB-HealthChecker/2.0"
[2017-11-20 19:12:03 +0000] [23741] [INFO] Worker exiting (pid: 23741)
/usr/local/lib/python3.6/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.
.format(x=modname), ExtDeprecationWarning

**Comment by Eronarn** [comment]
I am seeing this with:

```
def get_dag():
    with DAG(dag_id='nightly_dataload',
             start_date="2018-01-01",
             schedule_interval="@daily",
             concurrency=1,
             dagrun_timeout=timedelta(hours=24),
             default_args=default_args,
             ) as dag:
```

```
alembic==0.8.10
amqp==2.2.2
ansible-tower-cli==3.1.4
apache-airflow==1.9.0
asn1crypto==0.24.0
Babel==2.5.3
bcolz==0.12.1
bcrypt==3.1.4
billiard==3.5.0.3
bleach==2.1.2
boto==2.48.0
boto3==1.5.22
botocore==1.8.36
Bottleneck==1.2.1
celery==4.1.0
certifi==2017.11.5
cffi==1.11.4
chardet==3.0.4
click==6.7
colorama==0.3.9
configparser==3.5.0
contextlib2==0.5.5
croniter==0.3.20
cryptography==2.1.4
cyordereddict==1.0.0
Cython==0.27.3
decorator==4.2.1
dill==0.2.7.1
docutils==0.14
empyrical==0.3.3
filechunkio==1.8
Flask==0.11.1
Flask-Admin==1.4.1
Flask-Bcrypt==0.7.1
Flask-Cache==0.13.1
Flask-Login==0.2.11
flask-swagger==0.2.13
Flask-WTF==0.14
flower==0.9.2
funcsigs==1.0.0
future==0.16.0
gitdb2==2.0.3
GitPython==2.1.8
gunicorn==19.7.1
html5lib==1.0.1
humanize==0.5.1
idna==2.6
intervaltree==2.1.0
itsdangerous==0.24
Jinja2==2.8.1
jmespath==0.9.3
kombu==4.1.0
lockfile==0.12.2
Logbook==1.1.0
lru-dict==1.1.6
lxml==3.8.0
Mako==1.0.7
Markdown==2.6.11
MarkupSafe==1.0
multipledispatch==0.4.9
networkx==2.0
numexpr==2.6.4
numpy==1.14.0
ordereddict==1.1
pandas==0.18.1
pandas-datareader==0.5.0
patsy==0.5.0
psutil==4.4.2
psycopg2==2.7.3.2
pycparser==2.18
Pygments==2.2.0
python-daemon==2.1.2
python-dateutil==2.6.1
python-editor==1.0.3
python-interface==1.4.0
python-nvd3==0.14.2
python-slugify==1.1.4
pytz==2017.3
PyYAML==3.12
redis==2.10.6
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
s3transfer==0.1.12
scipy==1.0.0
setproctitle==1.1.10
six==1.11.0
slackclient==1.1.0
smmap2==2.0.3
sortedcontainers==1.5.9
SQLAlchemy==1.2.1
statsd==3.2.2
statsmodels==0.8.0
tables==3.4.2
tabulate==0.7.7
thrift==0.9.3
toolz==0.9.0
tornado==4.5.3
Unidecode==1.0.22
urllib3==1.22
vine==1.1.4
webencodings==0.5.1
websocket-client==0.46.0
Werkzeug==0.14.1
WTForms==2.1
zipline==1.1.1
zope.deprecation==4.3.0
```
