### ISSUE TITLE
Cannot scale worker=5 with docker-compose

### ISSUE THREAD

**Issue by Paw2Pom** [puckel/docker-airflow#150]
I have started two terminals.

First terminal:
docker-compose \
  -f docker-compose.yml \
  up

Second terminal:
docker-compose \
  -f docker-compose.yml \
  up -d --scale worker=5

===========
The result is that, both webserver and flower stopped working, and each of the worker generated the following error log:

worker_2     | [2018-01-19 17:01:28,972] {{__init__.py:45}} INFO - Using executor CeleryExecutor
worker_2     | [2018-01-19 17:01:33,683: CRITICAL/MainProcess] Unrecoverable error: OSError(12, 'Cannot allocate memory')
worker_2     | Traceback (most recent call last):
worker_2     |   File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 203, in start
worker_2     |     self.blueprint.start(self)
worker_2     |   File "/usr/local/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
worker_2     |     step.start(parent)
worker_2     |   File "/usr/local/lib/python3.6/site-packages/celery/bootsteps.py", line 370, in start
worker_2     |     return self.obj.start()
worker_2     |   File "/usr/local/lib/python3.6/site-packages/celery/concurrency/base.py", line 131, in start
worker_2     |     self.on_start()
worker_2     |   File "/usr/local/lib/python3.6/site-packages/celery/concurrency/prefork.py", line 112, in on_start
worker_2     |     **self.options)
worker_2     |   File "/usr/local/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 422, in __init__
worker_2     |     super(AsynPool, self).__init__(processes, *args, **kwargs)
worker_2     |   File "/usr/local/lib/python3.6/site-packages/billiard/pool.py", line 1007, in __init__
worker_2     |     self._create_worker_process(i)
worker_2     |   File "/usr/local/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 439, in _create_worker_process
worker_2     |     return super(AsynPool, self)._create_worker_process(i)
worker_2     |   File "/usr/local/lib/python3.6/site-packages/billiard/pool.py", line 1116, in _create_worker_process
worker_2     |     w.start()
worker_2     |   File "/usr/local/lib/python3.6/site-packages/billiard/process.py", line 124, in start
worker_2     |     self._popen = self._Popen(self)
worker_2     |   File "/usr/local/lib/python3.6/site-packages/billiard/context.py", line 333, in _Popen
worker_2     |     return Popen(process_obj)
worker_2     |   File "/usr/local/lib/python3.6/site-packages/billiard/popen_fork.py", line 24, in __init__
worker_2     |     self._launch(process_obj)
worker_2     |   File "/usr/local/lib/python3.6/site-packages/billiard/popen_fork.py", line 72, in _launch
worker_2     |     self.pid = os.fork()
worker_2     | OSError: [Errno 12] Cannot allocate memory
worker_2     |
worker_2     |  -------------- celery@0547251411f9 v4.0.2 (latentcall)
worker_2     | ---- **** -----
worker_2     | --- * ***  * -- Linux-4.4.0-109-generic-x86_64-with-debian-8.10 2018-01-19 17:01:29
worker_2     | -- * - **** ---
worker_2     | - ** ---------- [config]
worker_2     | - ** ---------- .> app:         airflow.executors.celery_executor:0x7f005ef6e780
worker_2     | - ** ---------- .> transport:   redis://redis:6379/1
worker_2     | - ** ---------- .> results:     postgresql://airflow:**@postgres:5432/airflow
worker_2     | - *** --- * --- .> concurrency: 16 (prefork)
worker_2     | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
worker_2     | --- ***** -----
worker_2     |  -------------- [queues]
worker_2     |                 .> default          exchange=default(direct) key=default
worker_2     |
worker_2     |
worker_2     | [2018-01-19 17:01:47,390] {{__init__.py:45}} INFO - Using executor CeleryExecutor
worker_2     | [2018-01-19 17:01:49,811: CRITICAL/MainProcess] Unrecoverable error: OSError(12, 'Cannot allocate memory')
worker_2     | Traceback (most recent call last):
worker_2     |   File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 203, in start
worker_2     |     self.blueprint.start(self)
worker_2     |   File "/usr/local/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
worker_2     |     step.start(parent)
worker_2     |   File "/usr/local/lib/python3.6/site-packages/celery/bootsteps.py", line 370, in start
worker_2     |     return self.obj.start()
worker_2     |   File "/usr/local/lib/python3.6/site-packages/celery/concurrency/base.py", line 131, in start
worker_2     |     self.on_start()
worker_2     |   File "/usr/local/lib/python3.6/site-packages/celery/concurrency/prefork.py", line 112, in on_start
worker_2     |     **self.options)
worker_2     |   File "/usr/local/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 422, in __init__
worker_2     |     super(AsynPool, self).__init__(processes, *args, **kwargs)
worker_2     |   File "/usr/local/lib/python3.6/site-packages/billiard/pool.py", line 1007, in __init__
worker_2     |     self._create_worker_process(i)
worker_2     |   File "/usr/local/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 439, in _create_worker_process
worker_2     |     return super(AsynPool, self)._create_worker_process(i)
worker_2     |   File "/usr/local/lib/python3.6/site-packages/billiard/pool.py", line 1116, in _create_worker_process
worker_2     |     w.start()
worker_2     |   File "/usr/local/lib/python3.6/site-packages/billiard/process.py", line 124, in start
worker_2     |     self._popen = self._Popen(self)
worker_2     |   File "/usr/local/lib/python3.6/site-packages/billiard/context.py", line 333, in _Popen
worker_2     |     return Popen(process_obj)
worker_2     |   File "/usr/local/lib/python3.6/site-packages/billiard/popen_fork.py", line 24, in __init__
worker_2     |     self._launch(process_obj)
worker_2     |   File "/usr/local/lib/python3.6/site-packages/billiard/popen_fork.py", line 72, in _launch
worker_2     |     self.pid = os.fork()
worker_2     | OSError: [Errno 12] Cannot allocate memory
worker_2     |
worker_2     |  -------------- celery@0547251411f9 v4.0.2 (latentcall)
worker_2     | ---- **** -----
worker_2     | --- * ***  * -- Linux-4.4.0-109-generic-x86_64-with-debian-8.10 2018-01-19 17:01:47
worker_2     | -- * - **** ---
worker_2     | - ** ---------- [config]
worker_2     | - ** ---------- .> app:         airflow.executors.celery_executor:0x7f08eece7668
worker_2     | - ** ---------- .> transport:   redis://redis:6379/1
worker_2     | - ** ---------- .> results:     postgresql://airflow:**@postgres:5432/airflow
worker_2     | - *** --- * --- .> concurrency: 16 (prefork)
worker_2     | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
worker_2     | --- ***** -----
worker_2     |  -------------- [queues]
worker_2     |                 .> default          exchange=default(direct) key=default
worker_2     |
worker_2     |

**Comment by Paw2Pom** [comment]
Latest updated made scale works!!! Amazing!
