### ISSUE TITLE
Encoding issue when opening a log from example_http_operator

### ISSUE THREAD

**Issue by kmevissen** [puckel/docker-airflow#16]
I'm having a small issue with opening logs for the post_op task in the example_http_operator DAG. This seems to work fine on my local machine running with SequentialExecutor, but after a fresh setup with the docker container it seems to crash.

I tried a bunch of things including setting the locales in the Dockerfile but that doesn't seem to help. I'm a bit lost whether this is my own incapabilities (new to Docker) or if this is reproduceable by someone else.

The following stacktrace is displayed when opening a log from the failed post_op task:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/flask_admin/base.py", line 359, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/flask_login.py", line 755, in decorated_view
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/airflow/www/utils.py", line 103, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/airflow/www/views.py", line 786, in log
    log = log.decode('utf-8') if PY2 else log
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 5872: ordinal not in range(128)

**Comment by puckel** [comment]
Hi,
Yes seems the same as https://github.com/airbnb/airflow/issues/731
I've tested with other mysql container and also with locale configuration but the problem persist.

**Comment by kmevissen** [comment]
Actually it doesn't seem related to the underlying data storage. In fact the logs are read from disk directly from the worker container [here](https://github.com/airbnb/airflow/blob/master/airflow/www/views.py#L762).

I haven't really looked into it in much depth, but it seems the object returned is of type unicode. I believe instead of calling the decode method on [this line](https://github.com/airbnb/airflow/blob/master/airflow/www/views.py#L794), the encode method should be called instead, to create a utf-8 str object. In that case the ascii characters should render fine.

**Comment by puckel** [comment]
I've pushed in master docker-airflow now based on Debian stable (Jessie) still the issue.

**Comment by kmevissen** [comment]
I've added a small bugfix to fix this encoding issue, PR is already merged:

https://github.com/airbnb/airflow/pull/925

Basically the remote call to the airflow worker returned an object already in unicode, so it doesn't have to be decoded to utf-8 anymore.
