### ISSUE TITLE
flower service fails on vanilla 'docker-compose up'

### ISSUE THREAD

**Issue by astewart-twist** [puckel/docker-airflow#19]
```
flower_1    | [2016-03-24 00:43:30,633] {__init__.py:36} INFO - Using executor CeleryExecutor
flower_1    | Traceback (most recent call last):
flower_1    |   File "/usr/local/bin/flower", line 5, in <module>
flower_1    |     from pkg_resources import load_entry_point
flower_1    |   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
flower_1    |     working_set = WorkingSet._build_master()
flower_1    |   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
flower_1    |     return cls._build_from_requirements(__requires__)
flower_1    |   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
flower_1    |     dists = ws.resolve(reqs, Environment())
flower_1    |   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
flower_1    |     raise DistributionNotFound(req)
flower_1    | pkg_resources.DistributionNotFound: pytz==2015.7
dockerairflow_flower_1 exited with code 0
```

**Comment by astewart-twist** [comment]
Disregard, duplicate of https://github.com/puckel/docker-airflow/issues/18

**Comment by astewart-twist** [comment]
Disregard the disregard.  The error still occurs.

**Comment by puckel** [comment]
I pushed the fix.
fyi, It's not the same issue as 18, it's a problem with installed version of pytz.

`pkg_resources.DistributionNotFound: pytz==2015.7`

The version installed in the docker image was `pytz==2016.1`.
