### ISSUE TITLE
branch: kubernetes   AttributeError: module 'pip' has no attribute 'get_installed_distributions'

### ISSUE THREAD

**Issue by samsema4** [puckel/docker-airflow#194]
As of Thu Jun  7 12:36:50 IST 2018

## Build failed! 

Command: docker build --rm -t puckel/docker-airflow .

## Error Logs:
```
......
......
+ buildDeps=         python3-dev         libkrb5-dev         libsasl2-dev         libssl-dev         libffi-dev         build-essential         libblas-dev         liblapack-dev         libpq-dev         git
+ apt-get update -yqq
+ apt-get install -yqq --no-install-recommends python3-dev libkrb5-dev libsasl2-dev libssl-dev libffi-dev build-essential libblas-dev liblapack-dev libpq-dev git python3-pip python3-requests apt-utils curl netcat locales


perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = "en_US.UTF-8",
	LC_CTYPE = "en_US.UTF-8",
	LC_MESSAGES = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
debconf: delaying package configuration, since apt-utils is not installed
......
......
Selecting previously unselected package apt-utils.
Preparing to unpack .../02-apt-utils_1.4.8_amd64.deb ...
Unpacking apt-utils (1.4.8) ...
......
......
Requirement already satisfied: pyasn1 in /usr/local/lib/python3.6/site-packages (0.4.3)
+ pip install apache-airflow[crypto,celery,postgres,hive,jdbc]==1.8.2
Collecting apache-airflow[celery,crypto,hive,jdbc,postgres]==1.8.2
  Downloading https://files.pythonhosted.org/packages/f1/83/a5fc6da0ced7c06f080b9b423b3483a926e7a387892a9013ec12229a0a89/apache-airflow-1.8.2.tar.gz (2.3MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-y9ahl221/apache-airflow/setup.py", line 302, in <module>
        do_setup()
      File "/tmp/pip-install-y9ahl221/apache-airflow/setup.py", line 198, in do_setup
        check_previous()
      File "/tmp/pip-install-y9ahl221/apache-airflow/setup.py", line 105, in check_previous
        in pip.get_installed_distributions()])
    AttributeError: module 'pip' has no attribute 'get_installed_distributions'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-y9ahl221/apache-airflow/
The command '/bin/sh -c set -ex     && buildDeps='         python3-dev         libkrb5-dev         libsasl2-dev         libssl-dev         libffi-dev         build-essential         libblas-dev         liblapack-dev         libpq-dev         git     '     && apt-get update -yqq     && apt-get install -yqq --no-install-recommends         $buildDeps         python3-pip         python3-requests         apt-utils         curl         netcat         locales     && sed -i 's/^# en_US.UTF-8 UTF-8$/en_US.UTF-8 UTF-8/g' /etc/locale.gen     && locale-gen     && update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8     && useradd -ms /bin/bash -d ${AIRFLOW_HOME} airflow     && python -m pip install -U pip setuptools wheel     && pip install Cython     && pip install pytz     && pip install pyOpenSSL     && pip install ndg-httpsclient     && pip install pyasn1     && pip install apache-airflow[crypto,celery,postgres,hive,jdbc]==$AIRFLOW_VERSION     && pip install celery[redis]==3.1.17     && apt-get purge --auto-remove -yqq $buildDeps     && apt-get clean     && rm -rf         /var/lib/apt/lists/*         /tmp/*         /var/tmp/*         /usr/share/man         /usr/share/doc         /usr/share/doc-base' returned a non-zero code: 1
make: *** [build] Error 1
```

I used '......' to indicate there other successful installation logs.

**Comment by samsema4** [comment]
Not sure if this is right fix for the problem, but from following source I found using pip 9.0.3, instead of available latest pip 10 will help fix the problem.

I have updated the docker file as follows (appreciated if you can tell me a better way to do it.)
```
diff --git a/Dockerfile b/Dockerfile
index 067bcdd..0cf807a 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -51,6 +51,7 @@ RUN set -ex \
     && useradd -ms /bin/bash -d ${AIRFLOW_HOME} airflow \
     && python -m pip install -U pip setuptools wheel \
     && pip install Cython \
+    && pip install pip==9.0.3 \
     && pip install pytz \
     && pip install pyOpenSSL \
     && pip install ndg-httpsclient \
```

[Pip 10 Compatibility Issue](https://github.com/Miserlou/Zappa/issues/1478)

**Comment by puckel** [comment]
Kubernetes branch is not supported
