### ISSUE TITLE
Airflow Scheduler not working using Local Executor

### ISSUE THREAD

**Issue by chandimsett** [puckel/docker-airflow#235]
I changed the airflow.cfg file:
sql_alchemy_conn = postgresql+psycopg2://airflow:airflow@localhost:5432/airflow
and 
executor = LocalExecutor
And then started the airflow server. I did bash inside the airflow container and ran airflow scheduler
Following exception was thrown:

```
 SAWarning: Session's state has been changed on a non-active transaction - this state will be discarded.
  "Session's state has been changed on "
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 32, in <module>
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/airflow/utils/cli.py", line 74, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airflow/bin/cli.py", line 925, in scheduler
    job.run()
  File "/usr/local/lib/python3.6/site-packages/airflow/jobs.py", line 196, in run
    session.commit()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 927, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 465, in commit
    self._assert_active(prepared_ok=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.OperationalError) could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
```
Can you help me configure the docker services to get the postgress connection up and running so that I can start airflow scheduler.

**Comment by guizsantos** [comment]
Just as a comment for peopole running into this in the future: @chandimsett solution probably only worked because the postgres container was launched under the id "postgres" _and_ in the same user-defined network as the airflow container... So if you are looking for this that is probably what you want to do.
