### ISSUE TITLE
Password authentication failed for user "airflow" when using non-default password

### ISSUE THREAD

**Issue by hasel-kinkajou** [puckel/docker-airflow#255]
I'm trying to set up Airflow with LocalExecutor and with non-default PostgreSQL password (for security perspective).

I made following changes to the files:

docker-compose-LocalExecutor.yml
```
version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=newPassw0rd
            - POSTGRES_DB=airflow
```

entrypoint.sh
```
: "${POSTGRES_HOST:="postgres"}"
: "${POSTGRES_PORT:="5432"}"
: "${POSTGRES_USER:="airflow"}"
: "${POSTGRES_PASSWORD:="newPassw0rd"}"
: "${POSTGRES_DB:="airflow"}"
```

I expected everything to work with just this, but when trying to deploy the containers with `docker-compose -f docker-compose-LocalExecutor.yml up` I get authentication error. Below is a part of the docker-compose log.

```
webserver_1  |
webserver_1  |   ____________       _____________
webserver_1  |  ____    |__( )_________  __/__  /________      __
webserver_1  | ____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
webserver_1  | ___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
webserver_1  |  _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
webserver_1  |
webserver_1  | [2018-10-26 09:13:09,710] {{models.py:258}} INFO - Filling up the DagBag from /usr/local/airflow/dags
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/local/bin/airflow", line 32, in <module>
webserver_1  |     args.func(args)
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/utils/cli.py", line 74, in wrapper
webserver_1  |     return f(*args, **kwargs)
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/bin/cli.py", line 790, in webserver
webserver_1  |     app = cached_app_rbac(conf) if settings.RBAC else cached_app(conf)
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/www/app.py", line 184, in cached_app
webserver_1  |     app = create_app(config, testing)
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/www/app.py", line 69, in create_app
webserver_1  |     from airflow.www import views
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/www/views.py", line 2195, in <module>
webserver_1  |     class ChartModelView(wwwutils.DataProfilingMixin, AirflowModelView):
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/www/views.py", line 2286, in ChartModelView
webserver_1  |     'conn_id': _connection_ids()
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
webserver_1  |     return func(*args, **kwargs)
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/www/views.py", line 2190, in _connection_ids
webserver_1  |     .group_by(models.Connection.conn_id)
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
webserver_1  |     return self._execute_and_instances(context)
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2876, in _execute_and_instances
webserver_1  |     close_with_result=True)
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2885, in _get_bind_args
webserver_1  |     **kw
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2867, in _connection_from_session
webserver_1  |     conn = self.session.connection(**kw)
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1019, in connection
webserver_1  |     execution_options=execution_options)
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1024, in _connection_for_bind
webserver_1  |     engine, execution_options)
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 388, in _connection_for_bind
webserver_1  |     self._assert_active()
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
webserver_1  |     % self._rollback_exception
webserver_1  | sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.OperationalError) FATAL:  password authentication failed for user "airflow"
webserver_1  |
postgres_1   | LOG:  incomplete startup packet
postgres_1   | FATAL:  password authentication failed for user "airflow"
postgres_1   | DETAIL:  Password does not match for user "airflow".
postgres_1   |  Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1   | FATAL:  password authentication failed for user "airflow"
postgres_1   | DETAIL:  Password does not match for user "airflow".
postgres_1   |  Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1   | FATAL:  password authentication failed for user "airflow"
postgres_1   | DETAIL:  Password does not match for user "airflow".
postgres_1   |  Connection matched pg_hba.conf line 95: "host all all all md5"
airflow_webserver_1 exited with code 1
```

I have confirmed that the user is created in PostgreSQL-container by going inside it with `docker exec` and `psql`. I have also tried to set `AIRFLOW__CORE__SQL_ALCHEMY_CONN` without variables in entrypoint.sh, setting it in environment variable in docker-compose file and configuring it directly in airflow.cfg but nothing seems to help.

Interesting interaction is that, if I remove `POSTGRES_PASSWORD=newPassw0rd` from docker-compose but leave the new password in entrypoint.sh, then the connection works.

I'm starting to feel that there's something obvious that I'm overlooking but running out of ideas. What other changes need to be made to change the password?

**Comment by KimchaC** [comment]
First of all you don't need to modify entrypoint.sh since it accepts env variables.

But you do need to set the password in both the postgres and the webserver sections of your docker-compose.yml:

```
version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=newPassw0rd # ** CHANGE HERE **
            - POSTGRES_DB=airflow

    webserver:
        image: puckel/docker-airflow:1.10.0-4
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - POSTGRES_PASSWORD=newPassw0rd  # ** CHANGE HERE **
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

**Comment by hasel-kinkajou** [comment]
Thank you this worked, but I don't understand why.

If I don't pass the environment variable in compose for the webserver, but change it in the `entrypoint.sh` so it defaults to it if not set, shouldn't the new password be available then? The end result should be the same with both ways.
