### ISSUE TITLE
Scheduler unstable

### ISSUE THREAD

**Issue by gsvijayraajaa** [puckel/docker-airflow#28]
Hi,

   Thanks for the docker image. When I run a pipeline , more often I find that the scheduler is quite unstable., it starts of with the error : ERROR - [Errno 104] Connection reset by peer   

The error log for your ref;

ERROR - [Errno 104] Connection reset by peer
2016-06-17T11:42:51.799483436Z Traceback (most recent call last):
2016-06-17T11:42:51.799494203Z   File "/usr/local/lib/python2.7/dist-packages/airflow/jobs.py", line 755, in _execute
2016-06-17T11:42:51.799501615Z     executor.heartbeat()
2016-06-17T11:42:51.799507897Z   File "/usr/local/lib/python2.7/dist-packages/airflow/executors/base_executor.py", line 107, in heartbeat
2016-06-17T11:42:51.799514286Z     self.sync()
2016-06-17T11:42:51.799520586Z   File "/usr/local/lib/python2.7/dist-packages/airflow/executors/celery_executor.py", line 74, in sync
2016-06-17T11:42:51.799527236Z     state = async.state
2016-06-17T11:42:51.799533355Z   File "/usr/local/lib/python2.7/dist-packages/celery/result.py", line 394, in state
2016-06-17T11:42:51.799540325Z     return self._get_task_meta()['status']
2016-06-17T11:42:51.799546778Z   File "/usr/local/lib/python2.7/dist-packages/celery/result.py", line 339, in _get_task_meta
2016-06-17T11:42:51.799553135Z     return self._maybe_set_cache(self.backend.get_task_meta(self.id))
2016-06-17T11:42:51.799559187Z   File "/usr/local/lib/python2.7/dist-packages/celery/backends/amqp.py", line 163, in get_task_meta
2016-06-17T11:42:51.799565969Z     binding.declare()
2016-06-17T11:42:51.799571830Z   File "/usr/local/lib/python2.7/dist-packages/kombu/entity.py", line 521, in declare
2016-06-17T11:42:51.799578902Z     self.exchange.declare(nowait)
2016-06-17T11:42:51.799585186Z   File "/usr/local/lib/python2.7/dist-packages/kombu/entity.py", line 174, in declare
2016-06-17T11:42:51.799591931Z     nowait=nowait, passive=passive,
2016-06-17T11:42:51.799598206Z   File "/usr/local/lib/python2.7/dist-packages/amqp/channel.py", line 615, in exchange_declare
2016-06-17T11:42:51.799604873Z     self._send_method((40, 10), args)
2016-06-17T11:42:51.799611275Z   File "/usr/local/lib/python2.7/dist-packages/amqp/abstract_channel.py", line 56, in _send_method
2016-06-17T11:42:51.799631815Z     self.channel_id, method_sig, args, content,
2016-06-17T11:42:51.799639848Z   File "/usr/local/lib/python2.7/dist-packages/amqp/method_framing.py", line 221, in write_method
2016-06-17T11:42:51.799646601Z     write_frame(1, channel, payload)
2016-06-17T11:42:51.799652763Z   File "/usr/local/lib/python2.7/dist-packages/amqp/transport.py", line 182, in write_frame
2016-06-17T11:42:51.799659065Z     frame_type, channel, size, payload, 0xce,
2016-06-17T11:42:51.799665133Z   File "/usr/lib/python2.7/socket.py", line 224, in meth
2016-06-17T11:42:51.799671254Z     return getattr(self._sock,name)(*args)
2016-06-17T11:42:51.799676859Z error: [Errno 104] Connection reset by peer
2016-06-17T11:42:51.799967150Z [2016-06-17 11:42:51,799] {jobs.py:759} ERROR - Tachycardia!
2016-06-17T11:45:01.136584726Z Fri Jun 17 11:45:01 UTC 2016 - waiting for RabbitMQ... 1/10
2016-06-17T11:47:13.872341907Z Fri Jun 17 11:47:13 UTC 2016 - waiting for RabbitMQ... 2/10
2016-06-17T11:49:26.352538395Z Fri Jun 17 11:49:26 UTC 2016 - waiting for RabbitMQ... 3/10

Kindly direct me with the fix.

Regards,
Vijay Raajaa G S

**Comment by puckel** [comment]
Hi,

Can you provide me the full stack trace ? Because scheduler in configured to auto-restart after 5 runs in docker-compose.yml (ie: https://groups.google.com/forum/#!topic/airbnb_airflow/Bf-7YASKD2U)

**Comment by gsvijayraajaa** [comment]
I did figure that out and removed the parameter from the docker-compose.yml file. I think the connection to rabbitmq is getting lost during restarts. I am currently running two scheduler's for load balancing. What is the intuition behind the frequent restart?

Regards,
Vijay Raajaa GS
