### ISSUE TITLE
CeleryExecutor is not executing the jobs 

### ISSUE THREAD

**Issue by abhishek-kumar0409** [puckel/docker-airflow#326]
Team,

The task in the airflow are not getting scheduled because of the below mentioned error. I'm using docker-compose-CeleryExecutor.yml file to launch the airflow instance in my environment. 

**Observation:** 
The AIRFLOW-UI is coming up successfully but the jobs are not getting scheduled, this might be due to the fact that celery service is not functioning properly.

Can someone suggest any resolution for this ?

```
docker-airflow_flower_1 exited with code 1
flower_1     | Mon Mar 11 08:43:32 UTC 2019 - waiting for Postgres... 1/20
flower_1     | [2019-03-11 08:43:47,924] {{settings.py:174}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800, pid=1
flower_1     | [2019-03-11 08:43:48,540] {{__init__.py:51}} INFO - Using executor CeleryExecutor
flower_1     | Traceback (most recent call last):
flower_1     |   File "/usr/local/bin/flower", line 6, in <module>
flower_1     |     from flower.__main__ import main
flower_1     |   File "/usr/local/lib/python3.6/site-packages/flower/__main__.py", line 4, in <module>
flower_1     |     from flower.command import FlowerCommand
flower_1     |   File "/usr/local/lib/python3.6/site-packages/flower/command.py", line 18, in <module>
flower_1     |     from .app import Flower
flower_1     |   File "/usr/local/lib/python3.6/site-packages/flower/app.py", line 15, in <module>
flower_1     |     from .urls import handlers
flower_1     |   File "/usr/local/lib/python3.6/site-packages/flower/urls.py", line 9, in <module>
flower_1     |     from .api import tasks
flower_1     |   File "/usr/local/lib/python3.6/site-packages/flower/api/tasks.py", line 81, in <module>
flower_1     |     class TaskApply(BaseTaskHandler):
flower_1     |   File "/usr/local/lib/python3.6/site-packages/flower/api/tasks.py", line 83, in TaskApply
flower_1     |     @web.asynchronous
flower_1     | AttributeError: module 'tornado.web' has no attribute 'asynchronous'
flower_1     | [2019-03-11 08:44:02,530] {{settings.py:174}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800, pid=1
```

**Comment by abhishek-kumar0409** [comment]
Issue fixed temporarily by adding below lines in the docker file as suggested in #324 

```  
pip install apache-airflow[crypto,celery,postgres,hive,jdbc,mysql,ssh${AIRFLOW_DEPS:+,}${AIRFLOW_DEPS}]==${AIRFLOW_VERSION} \
**   && pip install "tornado>=4.2.0,<6.0.0" \**
**  && pip install 'redis~=3.2' \**
```
