### ISSUE TITLE
webserver is restarting forever when using image built locally. 

### ISSUE THREAD

**Issue by siddardha7** [puckel/docker-airflow#345]
**/entrypoint.sh webs…"   About a minute ago   Restarting (1) 25 seconds ago**

**webserver container log**

[2019-04-09 07:12:18,884] {{settings.py:174}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800, pid=1
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 21, in <module>
    from airflow import configuration
  File "/usr/local/lib/python3.6/site-packages/airflow/__init__.py", line 36, in <module>
    from airflow import settings, configuration as conf
  File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 266, in <module>
    configure_orm()
  File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 188, in configure_orm
    engine = create_engine(SQL_ALCHEMY_CONN, **engine_args)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 431, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 599, in dbapi
    import psycopg2
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: libpq.so.5: cannot open shared object file: No such file or directory

**Comment by guiase** [comment]
I´ve just face of the same problem, I did not fix but i could workaround it.
I opened Dockerfile and change AIRFLOW_VERSION arguments from 1.10.2 to 1.10.1
ARG AIRFLOW_VERSION=1.10.1
