### ISSUE TITLE
Entrypoint Passing Secret as Port into Flower

### ISSUE THREAD

**Issue by joshuap2613** [puckel/docker-airflow#408]
Receiving an error message, in flower and worker nodes
```
Traceback (most recent call last):
  File "/usr/local/bin/flower", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/flower/__main__.py", line 11, in main
    flower.execute_from_commandline()
  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 275, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.6/site-packages/flower/command.py", line 56, in handle_argv
    return self.run_from_argv(prog_name, argv)
  File "/usr/local/lib/python3.6/site-packages/flower/command.py", line 48, in run_from_argv
    self.print_banner('ssl_options' in settings)
  File "/usr/local/lib/python3.6/site-packages/flower/command.py", line 141, in print_banner
    logger.info('Broker: %s', self.app.connection().as_uri())
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 793, in connection
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 751, in connection_for_write
    return self._connection(url or self.conf.broker_write_url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 819, in _connection
    'broker_connection_timeout', connect_timeout
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 189, in __init__
    url_params = parse_url(hostname)
  File "/usr/local/lib/python3.6/site-packages/kombu/utils/url.py", line 47, in parse_url
    scheme, host, port, user, password, path, query = _parse_url(url)
  File "/usr/local/lib/python3.6/site-packages/kombu/utils/url.py", line 81, in url_to_parts
    parts.port,
  File "/usr/local/lib/python3.6/urllib/parse.py", line 169, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'ROZ'
```
After tracking down the issue, it appears that if we use `redis-secrets` in the `values.yaml` file -- `existingSecret: airflow-redis` then that secret is passed into the port for flower.

In fact, the issue appears to be in the image entry-point,
https://github.com/puckel/docker-airflow/blob/master/script/entrypoint.sh
line 40 is causing the problem
```
if [ -n "$REDIS_PASSWORD" ]; then
    REDIS_PREFIX=:${REDIS_PASSWORD}@
else
```
because the `REDIS_PREFIX` starts with an unnecessary colon
so later when
AIRFLOW__CELERY__BROKER_URL="redis://$REDIS_PREFIX$REDIS_HOST:$REDIS_PORT/1"
is run, the first part of the REDIS_PREFIX is a colon and the value after the colon is misinterpreted as the port. This leads to the error

**Comment by girishbin** [comment]
@joshuap2613  a "/" character in password  while creating a secret  in kubernetes triggers this. 
kubectl create secret generic airflow-postgres --from-literal=postgres-password=$(openssl rand -base64 13)

**Comment by MrZhaoAtBJ** [comment]
> @joshuap2613 a "/" character in password while creating a secret in kubernetes triggers this.
> kubectl create secret generic airflow-postgres --from-literal=postgres-password=$(openssl rand -base64 13)

Awesome! Thank you very much!

**Comment by matwerber1** [comment]
running into same issue - not clear how to solve for this... 

@joshuap2613 or others, did you find a fix? Is the "solution" (for testing, at least) to run Redis without a password?

**Comment by girishbin** [comment]
@matwerber1  please try with  a password which does not have "/" character in it. It should work.
