### ISSUE TITLE
Sending email fails with error ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by khjomaa** [puckel/docker-airflow#425]
Hi,

I'm running Airflow on CentOS 7 with CeleryExecutor mode and with following settings on the docker-compose file:

> extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      - EXECUTOR=Celery
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__SMTP__SMTP_HOST=${DOCKER_HOST_IP}
      - AIRFLOW__SMTP__SMTP_STARTTLS=False
      - AIRFLOW__SMTP__SMTP_SSL=False
      - AIRFLOW__SMTP__SMTP_PORT=25
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=${AIRFLOW_SMTP_EMAIL}

While **DOCKER_HOST_IP** is the IP of docker0 and used extra_hosts to add the docker0 ip to /etc/hosts file inside the container.
I want to connect from the container to sendmail which is running on docker host and listens to port 25.
But when task fails I see in the logs the following error message:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/airflow/models/__init__.py", line 1613, in handle_failure
    self.email_alert(error)
  File "/usr/local/lib/python3.6/site-packages/airflow/models/__init__.py", line 1829, in email_alert
    send_email(self.task.email, subject, html_content)
  File "/usr/local/lib/python3.6/site-packages/airflow/utils/email.py", line 55, in send_email
    mime_subtype=mime_subtype, mime_charset=mime_charset, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airflow/utils/email.py", line 101, in send_email_smtp
    send_MIME_email(smtp_mail_from, recipients, msg, dryrun)
  File "/usr/local/lib/python3.6/site-packages/airflow/utils/email.py", line 121, in send_MIME_email
    s = smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT) if SMTP_SSL else smtplib.SMTP(SMTP_HOST, SMTP_PORT)
  File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

I can ping the docker0 IP address from inside the container but when trying telnet it fails !

> root@a4deada5a098:/usr/local/airflow# cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.1      dockerhost
172.21.0.5      a4deada5a098
root@a4deada5a098:/usr/local/airflow# ping -c 2 dockerhost
PING dockerhost (172.17.0.1) 56(84) bytes of data.
64 bytes from dockerhost (172.17.0.1): icmp_seq=1 ttl=64 time=0.055 ms
64 bytes from dockerhost (172.17.0.1): icmp_seq=2 ttl=64 time=0.073 ms
--- dockerhost ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.055/0.064/0.073/0.009 ms
root@a4deada5a098:/usr/local/airflow# 
root@a4deada5a098:/usr/local/airflow# telnet dockerhost 25
Trying 172.17.0.1...
telnet: Unable to connect to remote host: Connection refused

What I'm doing wrong or missing ?

Please assist / advise.

**Comment by khjomaa** [comment]
I changed sendmail bind address to 0.0.0.0 instead of 127.0.0.1 and problem fixed
