### ISSUE TITLE
Broken DAG: [/path/to/dag.py] Timeout, PID: pid#

### ISSUE THREAD

**Issue by andrew-zatserkovny** [puckel/docker-airflow#454]
We've started getting the **'Broken DAG: [/path/to/dag.py] Timeout, PID: pid#'** on our UI and airflow.exceptions.AirflowTaskTimeout: Timeout errors during the DAG parsing stage. We use Airflow 1.10.4 with Celery executor, Redis broker and Postgres result backend. 

The typical traceback on looks as follows below:

`[2019-10-17 08:27:44,551] {dagbag.py:90} INFO - Filling up the DagBag from /usr/local/airflow/dags/providers/p10-monetization-facebook-ils/monetization_facebook_ils.py
[2019-10-17 08:27:45,873] {__init__.py:51} INFO - Using executor CeleryExecutor
[2019-10-17 08:27:46,181] {dagbag.py:90} INFO - Filling up the DagBag from /usr/local/airflow/dags/providers/p03-monetization-google-analytics-events/monetization_google_analytics_events.py
[2019-10-17 08:28:14,712] {timeout.py:42} ERROR - Process timed out, PID: 7010
[2019-10-17 08:28:15,415] {dagbag.py:205} ERROR - Failed to import: /usr/local/airflow/dags/providers/p10-monetization-facebook-ils/monetization_facebook_ils.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 202, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/providers/p10-monetization-facebook-ils/monetization_facebook_ils.py", line 4, in <module>
    from operators.providers.MonetizationProviderExtractOperator import MonetizationProviderExtractOperator
  File "/usr/local/airflow/utils/operators/providers/MonetizationProviderExtractOperator.py", line 6, in <module>
    from operators.providers.GetMonetizationJobIDandS3DestinationOperator import \
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 43, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 7010
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 32, in <module>
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 500, in run
    dag = get_dag(args)
  File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 146, in get_dag
    'parse.'.format(args.dag_id))
airflow.exceptions.AirflowException: dag_id could not be found: p10_provider_facebook_ils. Either the dag did not exist or it failed to parse.
[2019-10-17 08:28:18,539: ERROR/ForkPoolWorker-5] execute_command encountered a CalledProcessError
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/executors/celery_executor.py", line 67, in execute_command
    close_fds=True, env=env)
  File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['airflow', 'run', 'p10_provider_facebook_ils', 'truncate_staging_facebook_ils', '2019-10-17T02:00:00+00:00', '--local', '--pool', 'provider', '-sd', '/usr/local/airflow/dags/providers/p10-monetization-facebook-ils/monetization_facebook_ils.py']' returned non-zero exit status 1.
[2019-10-17 08:28:18,540: ERROR/ForkPoolWorker-5] None
[2019-10-17 08:28:18,547: ERROR/ForkPoolWorker-5] Task airflow.executors.celery_executor.execute_command[08c15249-a40f-4ce3-b608-8a787c60fedd] raised unexpected: AirflowException('Celery command failed')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/executors/celery_executor.py", line 67, in execute_command
    close_fds=True, env=env)
  File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['airflow', 'run', 'p10_provider_facebook_ils', 'truncate_staging_facebook_ils', '2019-10-17T02:00:00+00:00', '--local', '--pool', 'provider', '-sd', '/usr/local/airflow/dags/providers/p10-monetization-facebook-ils/monetization_facebook_ils.py']' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/executors/celery_executor.py", line 72, in execute_command
    raise AirflowException('Celery command failed')
airflow.exceptions.AirflowException: Celery command failed
[2019-10-17 08:28:25,292] {timeout.py:42} ERROR - Process timed out, PID: 7017
[2019-10-17 08:28:25,292] {dagbag.py:205} ERROR - Failed to import: /usr/local/airflow/dags/providers/p03-monetization-google-analytics-events/monetization_google_analytics_events.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 202, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/providers/p03-monetization-google-analytics-events/monetization_google_analytics_events.py", line 4, in <module>
    from operators.providers.MonetizationProviderExtractOperator import MonetizationProviderExtractOperator
  File "/usr/local/airflow/utils/operators/providers/MonetizationProviderExtractOperator.py", line 3, in <module>
    from operators.common.LoadS3CSVToMySQLTableOperator import LoadS3CSVToMySQLTableOperator
  File "/usr/local/airflow/utils/operators/common/LoadS3CSVToMySQLTableOperator.py", line 4, in <module>
    from s3.s3_utils import download_s3_file_to_temp_dir
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1368, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1408, in _fill_cache
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 43, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 7017
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 32, in <module>
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 500, in run
    dag = get_dag(args)
  File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 146, in get_dag
    'parse.'.format(args.dag_id))
airflow.exceptions.AirflowException: dag_id could not be found: p03_provider_google_analytics_events. Either the dag did not exist or it failed to parse.
[2019-10-17 08:28:26,745: ERROR/ForkPoolWorker-7] execute_command encountered a CalledProcessError
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/executors/celery_executor.py", line 67, in execute_command
    close_fds=True, env=env)
  File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['airflow', 'run', 'p03_provider_google_analytics_events', 'load_to_stage_google_analytics_events', '2019-10-17T05:00:00+00:00', '--local', '--pool', 'provider', '-sd', '/usr/local/airflow/dags/providers/p03-monetization-google-analytics-events/monetization_google_analytics_events.py']' returned non-zero exit status 1.
[2019-10-17 08:28:26,747: ERROR/ForkPoolWorker-7] None
[2019-10-17 08:28:26,760: ERROR/ForkPoolWorker-7] Task airflow.executors.celery_executor.execute_command[0f1c2544-7552-41de-8c80-df55cec2622a] raised unexpected: AirflowException('Celery command failed')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/executors/celery_executor.py", line 67, in execute_command
    close_fds=True, env=env)
  File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['airflow', 'run', 'p03_provider_google_analytics_events', 'load_to_stage_google_analytics_events', '2019-10-17T05:00:00+00:00', '--local', '--pool', 'provider', '-sd', '/usr/local/airflow/dags/providers/p03-monetization-google-analytics-events/monetization_google_analytics_events.py']' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/executors/celery_executor.py", line 72, in execute_command
    raise AirflowException('Celery command failed')
airflow.exceptions.AirflowException: Celery command failed`

For a bunch of DAGs (the list of them varies on each parsing iteration) we see the parsing fail with **'dag_id could not be found'** exception. The DAGs can be seen on the UI but the tasks execution drops with a timeout and the PIDs get killed after failing to pick up the DAG code.

The measures taken to remedy this issues included: 
- changing airflow.cfg parameters related to DAG parsing timeouts, webserver timeouts, concurrency and parallelism;
- number of workers and memory have been increased;
- the code has been massively refactored to simplify parsing and reduce the number of imports;
- availability of code is verified on the workers with all the dags present and paths being valid across scheduler and workers.

But the issue still persists. When run locally with a LocalExecutor we don't see the issue and the code does not seem to have any DAG parsing errors.

We would appreciate any advice on this issue. Thank you!

**Comment by andrew-zatserkovny** [comment]
The problem has been resolved by tweaking EFS params.

**Comment by FSalazarH** [comment]
Hi @andrew-zatserkovny , can you please tell details about the solution that you mentioned?

**Comment by andrew-zatserkovny** [comment]
Hey @FSalazarH , we changed EFS to provisioned mode with a rate of 1MB per sec.
