### ISSUE TITLE
ModuleNotFoundError: No module named 'kubernetes' 

### ISSUE THREAD

**Issue by fmunteanu** [puckel/docker-airflow#466]
Hi,

I'm using the KubernetesExecutor into a Helm chart with your image and I noticed this error message into `airflow-web` container:
```
waiting 60s... 
executing webserver... 
[2019-11-11 21:45:14,437] {{settings.py:213}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=1 
/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>. 
  """) 
Traceback (most recent call last): 
  File "/usr/local/bin/airflow", line 22, in <module> 
    from airflow.bin.cli import CLIFactory 
  File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 55, in <module> 
    from airflow import jobs, settings 
  File "/usr/local/lib/python3.7/site-packages/airflow/jobs/__init__.py", line 21, in <module> 
    from airflow.jobs.base_job import BaseJob  # noqa: F401 
  File "/usr/local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 48, in <module> 
    class BaseJob(Base, LoggingMixin): 
  File "/usr/local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 82, in BaseJob 
    executor=executors.get_default_executor(), 
  File "/usr/local/lib/python3.7/site-packages/airflow/executors/__init__.py", line 48, in get_default_executor 
    DEFAULT_EXECUTOR = _get_executor(executor_name) 
  File "/usr/local/lib/python3.7/site-packages/airflow/executors/__init__.py", line 85, in _get_executor 
    from airflow.contrib.executors.kubernetes_executor import KubernetesExecutor 
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/executors/kubernetes_executor.py", line 27, in <module> 
    import kubernetes 
ModuleNotFoundError: No module named 'kubernetes' 
```

I was wondering if you could provide some guidance how to address the issue. Ideally, I would like to pass the `AIRFLOW_DEPS='kubernetes'` into Helm chart?

Regards,

Floren

**Comment by fmunteanu** [comment]
I will do a `docker build --build-arg`, I believe I do not have other choice.
