### ISSUE TITLE
Docker build fails because of pymssql

### ISSUE THREAD

**Issue by Rolando-B** [puckel/docker-airflow#476]
I am trying to build the latest version of the docker image and got the following error during the build : 

```
Building wheels for collected packages: pendulum, pymssql
  Building wheel for pendulum (PEP 517): started
  Building wheel for pendulum (PEP 517): finished with status 'done'
  Created wheel for pendulum: filename=pendulum-1.4.4-cp37-cp37m-linux_x86_64.whl size=129068 sha256=a4dcdf3e9c88d2813e31549910b8fdaa73a77c98e6225497578c98897bdedcfa
  Stored in directory: /root/.cache/pip/wheels/2f/4c/cd/f0cabf03ccb7edd9002875db9001108b33ebfc60b4ff9a61ae
  Building wheel for pymssql (PEP 517): started
  Building wheel for pymssql (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpnt0dmlta
       cwd: /tmp/pip-install-xa4bjjke/pymssql
  Complete output (42 lines):
  running bdist_wheel
  running build
  installing to build/bdist.linux-x86_64/wheel
  running install
  /tmp/pip-build-env-qwl9y1f0/overlay/lib/python3.7/site-packages/setuptools/dist.py:46: DistDeprecationWarning: Do not call this function
    warnings.warn("Do not call this function", DistDeprecationWarning)
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 182, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-qwl9y1f0/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 209, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-qwl9y1f0/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 194, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-qwl9y1f0/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 237, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-qwl9y1f0/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 493, in <module>
      tests_require=['pytest', 'unittest2'],
    File "/tmp/pip-build-env-qwl9y1f0/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-qwl9y1f0/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 228, in run
      self.run_command('install')
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 449, in run
      raise DeprecationWarning(msg)
  DeprecationWarning: The pymssql project has been discontinued.  To install the last working released version, use a
  version specifier like "pymssql<3.0".  For details and alternatives see:
  https://github.com/pymssql/pymssql/issues/668
  ----------------------------------------
  ERROR: Failed building wheel for pymssql
  Running setup.py clean for pymssql
Successfully built pendulum
Failed to build pymssql
```

Then the final error is the following : 
```
ERROR: Could not build wheels for pymssql which use PEP 517 and cannot be installed directly
```
I used the following command to build the image
```
docker build --rm --build-arg AIRFLOW_DEPS="all" --build-arg PYTHON_DEPS="python-dateutil,google-api-python-client" -t image_name . 
```
As specified during the error, pymyssql has been discontinued : https://github.com/pymssql/pymssql/issues/668 and is no more maintained.

I am using macOS Mojave 10.14.6, if it helps.
I also tried launching `pip install pymssql<3.0` but nothing.

Anyone encountering the same issue ?

**Comment by swapniel99** [comment]
A temporary fix is to use `pip install pymssql==2.1.4`.
However going forward need to migrate to pyodbc.

**Comment by Rolando-B** [comment]
I uninstalled pymssql and reinstalled it in 2.1.4. Still have the exact same error.

**Comment by mathiaszahorcak** [comment]
Try adding `&& pip install pymssql==2.1.4 \` in Dockerfile and adding `pymssql` in `&& pip install apache-airflow[ ]` statements (add `pymssql` inside square brackets).
Make sure `pymssql` is not called on docker-compose via` AIRFLOW_DEPS` or `PYTHON_DEPS`.

**Comment by Rolando-B** [comment]
The build seems to finish correctly since the update to 1.10.7.
Closing the issue.

**Comment by shortcarver** [comment]
My fix is to change pymssql in my requirements.txt to be:

`pymssql @ git+https://github.com/matusvalo/pymssql.git@cython3_fix`

I got it from the PR that I found: https://github.com/pymssql/pymssql/pull/803/files
