### ISSUE TITLE
Airflow dag execution error

### ISSUE THREAD

**Issue by mangoman18** [puckel/docker-airflow#484]
My environment is Airflow running in Docker. Python 3.6 downgraded from 3.7 and Airflow 10.7 ->upgraded from 10.4 to try and solve this issue. Here is the error on docker logs airflow.  No dags are getting executed or scheduled or triggered although there are being correctly picked up and displayed on the web UI. 

 [2020-01-04 03:30:03,454] {{dagbag.py:90}} INFO - Filling up the DagBag from /usr/local/airflow/dags
[2020-01-04 03:30:06,753] {{dagbag.py:405}} ERROR - [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 389, in collect_dags
    safe_mode=safe_mode)
  File "/usr/local/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 210, in process_file
    zip_file = zipfile.ZipFile(filepath)
  File "/usr/local/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.6/zipfile.py", line 1216, in _RealGetContents
    fp.seek(self.start_dir, 0)
OSError: [Errno 22] Invalid argument

Thank you anyone who has encountered this issue before.

**Comment by anteverse** [comment]
@mangoman18 do you have an **__init__.py** file at the root of your zip? If yes, make sure to build the zip without it.

Try something like this:
```bash
zip -x __init__.py --include \*.py -r dags.zip *
```
