### ISSUE TITLE
Flower is always restarting

### ISSUE THREAD

**Issue by sdikby** [puckel/docker-airflow#49]
hi,
i am using the last version of this docker-airflow, and i noticed that flower is always restarting and i don't have acces to the webserver

HTTP/1.1 200 OK
 [2016-11-15 16:45:46,526] {__init__.py:36} INFO - Using executor CeleryExecutor
 [2016-11-15 16:45:46,584] {driver.py:120} INFO - Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
 [2016-11-15 16:45:46,607] {driver.py:120} INFO - Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
 Traceback (most recent call last):
   File "/usr/local/bin/airflow", line 15, in <module>
     args.func(args)
   File "/usr/local/lib/python2.7/dist-packages/airflow/bin/cli.py", line 576, in flower
     os.execvp("flower", ['flower', '-b', broka, port, api])
   File "/usr/lib/python2.7/os.py", line 346, in execvp
     _execvpe(file, args)
   File "/usr/lib/python2.7/os.py", line 382, in _execvpe
     func(fullname, *argrest)
 OSError: [Errno 2] No such file or directory

**Comment by puckel** [comment]
I think this issue is related with the fix deployed for issue #48 (pyhton package flower is no more present). 

Fix in progress

**Comment by sdikby** [comment]
@puckel i have just find a fix for that.Tested and works 
pip install pandas==0.18.1 \
    && pip install celery==3.1.23 \
    && pip install airflow[celery,postgres,hive,hdfs,jdbc]==$AIRFLOW_VERSION
like suggested by #48 but install celery before airflow to force this version and install the older version of panda because it seems there is issues with the version 0.19 (like suggested here #45)

**Comment by puckel** [comment]
New release fix the issue.

Thanks
