### ISSUE TITLE
Problem connecting to WEB UI after docker upgrade

### ISSUE THREAD

**Issue by vazl** [puckel/docker-airflow#491]
Hi,

Upgraded docker on Windows 10 today and now having issues with running container. The logs show the following error:

Running the Gunicorn Server with:
Workers: 4 sync
Host: 0.0.0.0:8080
Timeout: 120
Logfiles: - -
=================================================================
[2020-01-22 01:37:24 +0000] [20] [INFO] Starting gunicorn 19.9.0
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 223, in run
    super(Application, self).run()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 199, in run
    self.start()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 139, in start
    self.pidfile.create(self.pid)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/pidfile.py", line 39, in create
    os.rename(fname, self.fname)
OSError: [Errno 16] Device or resource busy: '/usr/local/airflow/tmp8m376uuo' -> '/usr/local/airflow/airflow-webserver.pid'
[2020-01-22 01:37:37,182] {scheduler_job.py:927} INFO - 1 tasks up for execution:

Did I miss something?

Thanks

**Comment by UJIN88** [comment]
I have the same problem, I also upgraded Docker recently. Please, is there any fix? I tried re-installing Docker but that didn't solve the issue.

**Comment by vazl** [comment]
The problem was fixed as follows:

  1.  Reinstalled Docker
  2.  Started container without any dags and only added them once airflow was running
