### ISSUE TITLE
Certain characters in POSTGRES_PASSWORD cause error in worker and flower container

### ISSUE THREAD

**Issue by matwerber1** [puckel/docker-airflow#506]
Hi, 

I deployed a Postgres backend on Amazon Aurora and the remaining containers on AWS Fargate. The webserver, scheduler, and redis containers were working correctly... however, the worker and flower containers were failing to run. 

Eventually, I realized that certain characters in the Postgres password were causing the error.

The password that was causing problems was: 

```
k?DID!<afzU2Xr#2H*+H96Dk6Vy1v?nT
```

The error was: 

```
[2020-03-01 20:44:06,502: CRITICAL/MainProcess] Unrecoverable error: ValueError("invalid literal for int() with base 10: 'k'")
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/celery/worker/worker.py", line 205, in start
  self.blueprint.start(self)
File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 115, in start
  self.on_start()
File "/usr/local/lib/python3.7/site-packages/celery/apps/worker.py", line 139, in on_start
  self.emit_banner()
File "/usr/local/lib/python3.7/site-packages/celery/apps/worker.py", line 154, in emit_banner
  ' \n', self.startup_info(artlines=not use_image))),
File "/usr/local/lib/python3.7/site-packages/celery/apps/worker.py", line 217, in startup_info
  results=self.app.backend.as_uri(),
File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 138, in as_uri
  url = maybe_sanitize_url(self.url or '')
File "/usr/local/lib/python3.7/site-packages/kombu/utils/url.py", line 121, in maybe_sanitize_url
  return sanitize_url(url, mask)
File "/usr/local/lib/python3.7/site-packages/kombu/utils/url.py", line 114, in sanitize_url
  return as_url(*_parse_url(url), sanitize=True, mask=mask)
File "/usr/local/lib/python3.7/site-packages/kombu/utils/url.py", line 81, in url_to_parts
  parts.port,
File "/usr/local/lib/python3.7/urllib/parse.py", line 169, in port
  port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'k'
```

It's only a guess, but since the `ValueError` calls out an invalid literal of `'k'`, my guess is that maybe the `?` in the password creates a problem. I'm not sure if there are other invalid characters. 

When I changed the password to only be alphanumeric, the worker container launched successfully.

**Comment by anteverse** [comment]
Hi @matwerber1 ,
That might be due to the combination of the username and the password, not just the password.
Could you let us know the username you are using?

**Comment by matwerber1** [comment]
Howdy! for the username, I was just using `airflow`.
