### ISSUE TITLE
[Question] No custom database connection after restarting Docker

### ISSUE THREAD

**Issue by jolo-dev** [puckel/docker-airflow#524]
Hi,

after restarting the Docker container, I lost my connection to a self created Database connection.
They are still showing on the list but it's not working. Here is my error output
`[2020-03-19 10:11:50,226] {{taskinstance.py:1128}} ERROR - 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/postgres_operator.py", line 65, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 162, in run
    with closing(self.get_conn()) as conn:
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/postgres_hook.py", line 71, in get_conn
    conn = self.get_connection(conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 84, in get_connection
    log.info("Using connection to: %s", conn.log_info())
  File "/usr/local/lib/python3.7/site-packages/airflow/models/connection.py", line 320, in log_info
    "XXXXXXXX" if self.password else None,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 353, in __get__
    retval = self.descriptor.__get__(instance, owner)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/connection.py", line 190, in get_password
    return fernet.decrypt(bytes(self._password, 'utf-8')).decode()
  File "/usr/local/lib/python3.7/site-packages/cryptography/fernet.py", line 171, in decrypt
    raise InvalidToken
cryptography.fernet.InvalidToken`

If I recreate the connection, it all works as expected.
Maybe anyone has a hint of what to do?

Thanks in advance!
Best

**Comment by CodingJonas** [comment]
Did you change your Fernet key before restarting the Docker container?
Once it changed Airflow is not able to read out connection informations created with the old Fernet key ([see this section](https://airflow.readthedocs.io/en/stable/howto/secure-connections.html#rotating-encryption-keys)).
By recreating the connection you recreate the information, but now encrypted with the new key, which eliminates the `InvalidToken`, since Airflow now has the right key for the connection information again :)

**Comment by jolo-dev** [comment]
Thank you.
Much appreciated.
I am struggling with the documentation tbh.
I have put my Fernet Key into the `airflow.cfg`. 
When I restart my Docker Container, I recreate a new fernet key by 
```python
from cryptography.fernet import Fernet
fernet_key= Fernet.generate_key()
print(fernet_key.decode()) # your fernet_key, keep it in secured place!
```
I guess that key I need to replace in my `airflow.cfg` and run `airflow rotate_fernet_key` which then  leads to the following error message
```python
File "/usr/local/lib/python3.7/site-packages/cryptography/fernet.py", line 160, in rotate
    raise InvalidToken
cryptography.fernet.InvalidToken
```
I don't get point **1**.
How can I set fernet_key to new_fernet_key,old_fernet_key?

Thanks for your support!
