### ISSUE TITLE
Fernet Token Failure when running tests

### ISSUE THREAD

**Issue by Schachte** [puckel/docker-airflow#541]
I'm getting this Fernet token failure every time I run my test. It's a simple file sensor test. I have fernet passed in an env var. per the docs.

```
airflow@33953d58498b:~$ airflow test forex_data_pipeline_v_1 is_forex_file_available 2019-01-01
[2020-04-19 05:15:30,524] {{__init__.py:51}} INFO - Using executor SequentialExecutor
[2020-04-19 05:15:30,525] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags
[2020-04-19 05:15:30,593] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline_v_1.is_forex_file_available 2019-01-01T00:00:00+00:00 [None]>
[2020-04-19 05:15:30,601] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline_v_1.is_forex_file_available 2019-01-01T00:00:00+00:00 [None]>
[2020-04-19 05:15:30,602] {{taskinstance.py:866}} INFO -
--------------------------------------------------------------------------------
[2020-04-19 05:15:30,602] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-19 05:15:30,602] {{taskinstance.py:868}} INFO -
--------------------------------------------------------------------------------
[2020-04-19 05:15:30,603] {{taskinstance.py:887}} INFO - Executing <Task(FileSensor): is_forex_file_available> on 2019-01-01T00:00:00+00:00
[2020-04-19 05:15:30,622] {{taskinstance.py:1128}} ERROR -
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/sensors/base_sensor_operator.py", line 107, in execute
    while not self.poke(context):
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/sensors/file_sensor.py", line 57, in poke
    hook = FSHook(self.fs_conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/hooks/fs_hook.py", line 39, in __init__
    self.basepath = conn.extra_dejson.get('path', '')
  File "/usr/local/lib/python3.7/site-packages/airflow/models/connection.py", line 338, in extra_dejson
    if self.extra:
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 356, in __get__
    retval = self.descriptor.__get__(instance, owner)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/connection.py", line 212, in get_extra
    return fernet.decrypt(bytes(self._extra, 'utf-8')).decode()
  File "/usr/local/lib/python3.7/site-packages/cryptography/fernet.py", line 171, in decrypt
    raise InvalidToken
cryptography.fernet.InvalidToken
```

**Comment by ashley-mallia** [comment]
Did you discover a solution for this? I'm getting the same error
