### ISSUE TITLE
build and run locally is not working 

### ISSUE THREAD

**Issue by lzhou519** [puckel/docker-airflow#558]
I'm pretty new to docker and airflow. I'm trying to run airflow with docker locally so that I can adjust the .cfg files. But right now I am just trying to run the original configuration correctly. So I downloaded the repo files locally on windows and I'm trying to run it on docker desktop. 

I built it with "docker build --rm -t airflow-image ." I think it built correctly Then I'm running it with "docker run -p 8080:8080 airflow-image", and I get several errors shown below. Has anyone seen this error before? I also attached the run log files. Any help would be appreciated. Thanks. 

[docker_issues3.txt](https://github.com/puckel/docker-airflow/files/4706427/docker_issues3.txt)

Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 37, in <module>
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 75, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 900, in webserver
    app = cached_app_rbac(None) if settings.RBAC else cached_app(None)
  File "/usr/local/lib/python3.7/site-packages/airflow/www/app.py", line 233, in cached_app
    app = create_app(config, testing)
  File "/usr/local/lib/python3.7/site-packages/airflow/www/app.py", line 103, in create_app
    models.Chart, Session, name="Charts", category="Data Profiling"))
  File "/usr/local/lib/python3.7/site-packages/flask_admin/contrib/sqla/view.py", line 330, in __init__
    menu_icon_value=menu_icon_value)
  File "/usr/local/lib/python3.7/site-packages/flask_admin/model/base.py", line 818, in __init__
    self._refresh_cache()
  File "/usr/local/lib/python3.7/site-packages/flask_admin/model/base.py", line 913, in _refresh_cache
    self._search_supported = self.init_search()
  File "/usr/local/lib/python3.7/site-packages/flask_admin/contrib/sqla/view.py", line 581, in init_search
    if tools.is_hybrid_property(self.model, name):
  File "/usr/local/lib/python3.7/site-packages/flask_admin/contrib/sqla/tools.py", line 209, in is_hybrid_property
    return last_name in get_hybrid_properties(last_model)
  File "/usr/local/lib/python3.7/site-packages/flask_admin/contrib/sqla/tools.py", line 190, in get_hybrid_properties
    for key, prop in inspect(model).all_orm_descriptors.items()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/inspection.py", line 73, in inspect
    "available for object of type %s" % type_
sqlalchemy.exc.NoInspectionAvailable: No inspection system is available for object of type <class 'method'>

**Comment by wittfabian** [comment]
See: https://github.com/puckel/docker-airflow/issues/535
