### ISSUE TITLE
EOFError

### ISSUE THREAD

**Issue by stevenpitts** [puckel/docker-airflow#588]
I'm running this on AWS ECS, connected to an RDS Postgres database.
I'm not sure if this is an airflow issue or a docker-airflow issue

```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
self.run()
File "/usr/local/lib/python3.7/site-packages/airflow/executors/local_executor.py", line 112, in run
key, command = self.task_queue.get()
File "<string>", line 2, in get
File "/usr/local/lib/python3.7/multiprocessing/managers.py", line 819, in _callmethod
kind, result = conn.recv()
File "/usr/local/lib/python3.7/multiprocessing/connection.py", line 250, in recv
buf = self._recv_bytes()
File "/usr/local/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
buf = self._recv(4)
File "/usr/local/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
raise EOFError
EOFError
```

I'm still able to access the web server, but the web server reports that the scheduler isn't running. What could be causing it?
I'm not using any plugins, and my dags directory is empty.
I'm using `EXECUTOR=Local`, `LOAD_EX=n`, and `AIRFLOW__WEBSERVER__WEB_SERVER_PORT=3000`

**Comment by stevenpitts** [comment]
Fixed it! You just need to allocate more memory to the container.
