### ISSUE TITLE
Issue with Installing PyICU package - build fails 

### ISSUE THREAD

**Issue by KPdir** [puckel/docker-airflow#632]
Hi folks, 

We use puckel/docker-airflow docker image and install some additional packages for our Airflow environment but we are facing an issue currently and thought people here might have some insight into source of the issue and/or how to resolve it. Our build started to fail in the last few days likely due to some dependency issue while installing Python packages. The issue seems to be from installing `PyICU>=2.4.2` which throws the error (pasted below). We are not directly installing `PyICU>=2.4.2`, it seems to be a dependency for one or more of the packages that we are installing (seems to be due to dbt package). 

It seems to be an issue with some ICU libraries not being present in the OS packages. However, I don't seem to be able to assume root privileges in the docker container so I could not attempt to install ICU packages using `apt-get install`. I'd appreciate very much if anyone has some insight into what might be causing this or how I could try to fix this. Thanks!

**Build Error:** 
```
Collecting PyICU>=2.4.2
  Downloading PyICU-2.6.tar.gz (233 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8dgw01nx/pyicu_992e4237781646dfa1cde010f397d294/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8dgw01nx/pyicu_992e4237781646dfa1cde010f397d294/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-90cy1jxv
         cwd: /tmp/pip-install-8dgw01nx/pyicu_992e4237781646dfa1cde010f397d294/
    Complete output (53 lines):
    (running 'icu-config --version')
    (running 'pkg-config --modversion icu-i18n')
    Traceback (most recent call last):
      File "/tmp/pip-install-8dgw01nx/pyicu_992e4237781646dfa1cde010f397d294/setup.py", line 63, in <module>
        ICU_VERSION = os.environ['ICU_VERSION']
      File "/usr/local/lib/python3.7/os.py", line 679, in __getitem__
        raise KeyError(key) from None
    KeyError: 'ICU_VERSION'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-8dgw01nx/pyicu_992e4237781646dfa1cde010f397d294/setup.py", line 66, in <module>
        ICU_VERSION = check_output(('icu-config', '--version')).strip()
      File "/tmp/pip-install-8dgw01nx/pyicu_992e4237781646dfa1cde010f397d294/setup.py", line 19, in check_output
        return subprocess_check_output(popenargs)
      File "/usr/local/lib/python3.7/subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "/usr/local/lib/python3.7/subprocess.py", line 488, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'icu-config': 'icu-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-8dgw01nx/pyicu_992e4237781646dfa1cde010f397d294/setup.py", line 69, in <module>
        ICU_VERSION = check_output(('pkg-config', '--modversion', 'icu-i18n')).strip()
      File "/tmp/pip-install-8dgw01nx/pyicu_992e4237781646dfa1cde010f397d294/setup.py", line 19, in check_output
        return subprocess_check_output(popenargs)
      File "/usr/local/lib/python3.7/subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "/usr/local/lib/python3.7/subprocess.py", line 488, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config': 'pkg-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8dgw01nx/pyicu_992e4237781646dfa1cde010f397d294/setup.py", line 74, in <module>
        ''')
    RuntimeError:
    Please install pkg-config on your system or set the ICU_VERSION environment
    variable to the version of ICU you have installed.
    
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/31/46/fa08c8efae2951e67681ec24319f789fc1a74e2096dd74373e34c79319de/PyICU-2.6.tar.gz#sha256=a9a5bf6833360f8f69e9375b91c1a7dd6e0c9157a42aee5bb7d6891804d96371 (from https://pypi.org/simple/pyicu/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Here's the list of python packages we are installing:
```
dbt>=0.14.0
airflow-dbt>=0.3.0
pandas>=0.24.2
pandas-gbq>=0.10.0
google-api-core>=1.8.1
google-api-python-client>=1.7.8
google-auth>=1.6.3
google-auth-httplib2>=0.0.3
google-auth-oauthlib>=0.3.0
google-cloud-bigquery>=1.11.2
google-cloud-bigtable>=0.31.0
google-cloud-container>=0.2.1
google-cloud-core>=0.28.1
google-cloud-logging>=1.9.1
google-cloud-monitoring>=0.31.1
google-cloud-spanner>=1.8.0
google-cloud-storage>=1.13.2
google-resumable-media>=0.3.2
googleapis-common-protos>=1.5.8
grpc-google-iam-v1>=0.11.4
grpcio>=1.19.0
grpcio-gcp>=0.2.2
pylint>=2.5.3
```

Here's the relevant excerpt from the Dockerfile we use to build the new image: 
```
FROM puckel/docker-airflow:latest

COPY ./dags ${AIRFLOW_HOME}/dags
COPY ./local-requirements.txt ${AIRFLOW_HOME}
RUN pip3 install -r ${AIRFLOW_HOME}/local-requirements.txt

ENV PATH=${AIRFLOW_HOME}/.local/bin:$PATH
```

**Comment by KPdir** [comment]
Hi folks, 

We were able to resolve this issue. I'll post here the way we resolved it below. If you find there is better ways to resolve it please leave a comment here for others who may encounter the same. 

Basically, updated our Dockerfile to install pkg-config and libicu-dev OS packages:
```
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install libicu-dev
RUN apt-get -y install pkg-config
```
If your user is airflow, you can switch to root to run the installs and then switch back to airflow using the USER command. Hope that helps!
