### ISSUE TITLE
"cannot import name viewkeys" on HEAD

### ISSUE THREAD

**Issue by Stibbons** [puckel/docker-airflow#80]
Just to warn you that updating your scrip to fetch the HEAD (given a COMMIT ID in the build args) gives the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 4, in <module>
    __import__('pkg_resources').run_script('airflow==1.9.0.dev0+apache.incubating', 'airflow')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/airflow-1.9.0.dev0+apache.incubating-py2.7.egg/EGG-INFO/scripts/airflow", line 28, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/airflow-1.9.0.dev0+apache.incubating-py2.7.egg/airflow/bin/cli.py", line 734, in webserver
    app = cached_app(conf)
  File "/usr/local/lib/python2.7/dist-packages/airflow-1.9.0.dev0+apache.incubating-py2.7.egg/airflow/www/app.py", line 161, in cached_app
    app = create_app(config)
  File "/usr/local/lib/python2.7/dist-packages/airflow-1.9.0.dev0+apache.incubating-py2.7.egg/airflow/www/app.py", line 60, in create_app
    from airflow.www import views
  File "/usr/local/lib/python2.7/dist-packages/airflow-1.9.0.dev0+apache.incubating-py2.7.egg/airflow/www/views.py", line 27, in <module>
    import bleach
  File "/usr/local/lib/python2.7/dist-packages/bleach-2.0.0-py2.7.egg/bleach/__init__.py", line 5, in <module>
    from bleach.linkifier import (
  File "/usr/local/lib/python2.7/dist-packages/bleach-2.0.0-py2.7.egg/bleach/linkifier.py", line 4, in <module>
    import html5lib
  File "build/bdist.linux-x86_64/egg/html5lib/__init__.py", line 16, in <module>
  File "build/bdist.linux-x86_64/egg/html5lib/html5parser.py", line 2, in <module>
ImportError: cannot import name viewkeys
```

**Comment by puckel** [comment]
Hi,
I'm only maintaining the current stable version.
Thanks
