### ISSUE TITLE
Ad hoc query fails - pandas compile issue 

### ISSUE THREAD

**Issue by nick-gray** [puckel/docker-airflow#87]
When running a simple query against athena (via jdbc) I get this error:

```
C extension: umpy.core.multiarray failed to import not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
```

![image](https://cloud.githubusercontent.com/assets/13723883/26284277/ac5bd8a0-3e7a-11e7-9a39-e51b393f068f.png)

Have you run into this issue before? I imagine we have to add a bunch of other dependencies or use something like conda instead of pip to manage all of the dependencies.

**Comment by nick-gray** [comment]
Also seeing that when hitting the charts

```
web-408895555-s87ph web 2017-05-21T13:16:57.609065217Z ImportError: C extension: umpy.core.multiarray failed to import not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
web-408895555-s87ph web 2017-05-21T13:16:57.609199602Z [2017-05-21 13:16:57,607] [64] {app.py:1587} ERROR - Exception on /admin/airflow/chart_data [GET]
web-408895555-s87ph web 2017-05-21T13:16:57.609211261Z Traceback (most recent call last):
web-408895555-s87ph web 2017-05-21T13:16:57.609216241Z   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
web-408895555-s87ph web 2017-05-21T13:16:57.609220292Z     response = self.full_dispatch_request()
web-408895555-s87ph web 2017-05-21T13:16:57.609224076Z   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
web-408895555-s87ph web 2017-05-21T13:16:57.609228642Z     rv = self.handle_user_exception(e)
web-408895555-s87ph web 2017-05-21T13:16:57.609232936Z   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
web-408895555-s87ph web 2017-05-21T13:16:57.60923747Z     reraise(exc_type, exc_value, tb)
web-408895555-s87ph web 2017-05-21T13:16:57.609241686Z   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
web-408895555-s87ph web 2017-05-21T13:16:57.60925163Z     rv = self.dispatch_request()
web-408895555-s87ph web 2017-05-21T13:16:57.609256113Z   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
web-408895555-s87ph web 2017-05-21T13:16:57.609260665Z     return self.view_functions[rule.endpoint](**req.view_args)
web-408895555-s87ph web 2017-05-21T13:16:57.609264938Z   File "/usr/local/lib/python2.7/dist-packages/flask_admin/base.py", line 69, in inner
web-408895555-s87ph web 2017-05-21T13:16:57.609268835Z     return self._run_view(f, *args, **kwargs)
web-408895555-s87ph web 2017-05-21T13:16:57.609272378Z   File "/usr/local/lib/python2.7/dist-packages/flask_admin/base.py", line 368, in _run_view
web-408895555-s87ph web 2017-05-21T13:16:57.609275972Z     return fn(self, *args, **kwargs)
web-408895555-s87ph web 2017-05-21T13:16:57.609279889Z   File "/usr/local/lib/python2.7/dist-packages/airflow/www/views.py", line 237, in decorated_function
web-408895555-s87ph web 2017-05-21T13:16:57.609284249Z     return f(*args, **kwargs)
web-408895555-s87ph web 2017-05-21T13:16:57.60928796Z   File "/usr/local/lib/python2.7/dist-packages/airflow/www/utils.py", line 219, in view_func
web-408895555-s87ph web 2017-05-21T13:16:57.609291864Z     return f(*args, **kwargs)
web-408895555-s87ph web 2017-05-21T13:16:57.60929527Z   File "/usr/local/lib/python2.7/dist-packages/airflow/www/views.py", line 298, in chart_data
web-408895555-s87ph web 2017-05-21T13:16:57.609299111Z     import pandas as pd
web-408895555-s87ph web 2017-05-21T13:16:57.609305035Z   File "/usr/local/lib/python2.7/dist-packages/pandas/__init__.py", line 35, in <module>
web-408895555-s87ph web 2017-05-21T13:16:57.609309892Z     "the C extensions first.".format(module))
web-408895555-s87ph web 2017-05-21T13:16:57.609314157Z ImportError: C extension: umpy.core.multiarray failed to import not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
```
